/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MAHKeyframe =
  | {
      brush?: BrushWithTransition | null;
      coords: CoordsWithTransition;
      intensity?: IntensityWithTransition | null;
      time: number;
      type: "standard";
    }
  | {
      brush?: BrushWithTransition | null;
      intensity?: IntensityWithTransition | null;
      time: number;
      type: "pause";
    };
export type MAHBrush =
  | {
      name: "Circle";
      params: {
        radius: number;
      };
    }
  | {
      name: "Line";
      params: {
        length: number;
        rotation: number;
        thickness: number;
      };
    };
export type MAHTransition =
  | {
      name: "Linear";
      params: {};
    }
  | {
      name: "Step";
      params: {};
    };
export type MAHIntensity =
  | {
      name: "Constant";
      params: {
        value: number;
      };
    }
  | {
      name: "Random";
      params: {
        max: number;
        min: number;
      };
    };
export type Projection = "plane" | "palm";

export interface MidAirHapticsAnimationFileFormat {
  $DATA_FORMAT: string;
  $REVISION: string;
  keyframes: MAHKeyframe[];
  name: string;
  projection: Projection;
  update_rate: number;
}
export interface BrushWithTransition {
  brush: MAHBrush;
  transition: MAHTransition;
}
export interface CoordsWithTransition {
  coords: MAHCoords;
  transition: MAHTransition;
}
/**
 * x and y are used for the xy coordinate system in the 2d designer. z is intended to be orthogonal to the phased array
 */
export interface MAHCoords {
  /**
   * in millimeters, [-100, 100]
   */
  x: number;
  /**
   * in millimeters, [-100, 100]
   */
  y: number;
  /**
   * in millimeters, [0, 100]
   */
  z: number;
}
export interface IntensityWithTransition {
  intensity: MAHIntensity;
  transition: MAHTransition;
}
